// Generated by GraphWalker (http://www.graphwalker.org)
package test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "main/resources/testautomation/VVS.graphml")
public interface VVS {

    @Vertex()
    void Ready();

    @Vertex()
    void Server_with_content();

    @Edge()
    void power_up_server();

    @Edge()
    void do_search();

    @Edge()
    void do_sign_out();

    @Vertex()
    void Server_with_valid_token();

    @Edge()
    void do_remove_content();

    @Edge()
    void do_sign_up();

    @Edge()
    void do_add_content();
}
